import { useHebrew } from "~/i18n";
import { radius, colors } from "./../../../constants/designConstants";
import { Platform, StyleSheet } from "react-native";
import { horizontalScale, verticalScale } from "~/constants/metrics";

const isIOS = Platform.OS === "ios";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingBottom: verticalScale(40),
  },
  header: {
    position: "relative",
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: isIOS ? "row-reverse" : "row",
  },
  circleWrapper: {
    width: 80,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 5.5,
    borderColor: colors.purpleLinear,
    borderRadius: 50,
    backgroundColor: colors.white,
    marginBottom: verticalScale(28),
  },
  circleWrapperBigger: {
    width: 100,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 5.5,
    borderColor: colors.purpleLinear,
    borderRadius: 50,
    backgroundColor: colors.white,
    marginBottom: verticalScale(28),
  },
  circleInner: {
    width: 62,
    height: 62,
    borderRadius: 41,
    backgroundColor: colors.purpleLinear,
    justifyContent: "center",
    alignItems: "center",
  },
  circleInnerBigger: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: colors.purpleLinear,
    justifyContent: "center",
    alignItems: "center",
  },
  headerContent: {
    width: "63%",
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderRadius: radius.main,
    shadowColor: "rgba(28, 16, 32, 0.1)",
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    paddingHorizontal: horizontalScale(25),
  },
  goBackContainer: {
    position: "absolute",
    left: 0,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: horizontalScale(20),
    backgroundColor: colors.white,
    borderRadius: radius.secondary,
  },
  containerWrapper: {
    position: "absolute",
    bottom: 0,
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    height: 640,
    paddingTop: verticalScale(28),
    paddingHorizontal: horizontalScale(30),
    backgroundColor: colors.white,
    borderRadius: radius.large,
  },
  content: {
    width: "100%",
    alignItems: isIOS ? "flex-end" : "flex-start",
  },
  title: {},
  subtitle: {
    marginTop: verticalScale(6),
    marginBottom: verticalScale(8),
  },
  contactsContainer: {
    width: "100%",
    justifyContent: "flex-start",
    marginTop: verticalScale(17),
  },
  contacts: {
    width: "100%",
    justifyContent: "flex-start",
  },
  contactsTitle: {
    marginBottom: verticalScale(17),
  },
  contactRow: {
    flexDirection: isIOS ? "row-reverse" : "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: verticalScale(7),

    borderRadius: 10,
  },
  contactRowActive: {
    backgroundColor: colors.whiteFocused,
  },
  userIcon: {
    height: 48,
    width: 48,
    borderRadius: 24,
  },
  emptyIcon: {
    height: 48,
    width: 48,
    borderRadius: 24,
    alignItems: "center",
    backgroundColor: colors.purpleLinear,
    position: "relative",
    overflow: "hidden",
  },
  empty: {
    position: "absolute",
    bottom: -2,
  },
  contactName: {
    marginLeft: isIOS ? horizontalScale(5) : horizontalScale(15),
    marginRight: isIOS ? horizontalScale(15) : horizontalScale(5),
  },
  noMatches: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(30),
  },
  button: {
    width: "100%",
    marginBottom: verticalScale(30),
  },
  contentWrapper: {
    marginTop: verticalScale(36),
    width: "100%",
    paddingHorizontal: horizontalScale(20),
    alignItems: "center",
  },
  benefitsWrapper: {
    width: "100%",
    marginTop: verticalScale(28),
    alignItems: isIOS ? "flex-end" : "flex-start",
  },
  benefRow: {
    flexDirection: isIOS ? "row-reverse" : "row",
    alignItems: "center",
    marginBottom: verticalScale(9),
  },
  benefText: {
    width: 300,
    marginRight: isIOS ? horizontalScale(7) : horizontalScale(0),
    marginLeft: horizontalScale(7),
  },
  secondText: {
    flexDirection: "row",
    alignItems: "center",
  },
  introButton: {
    width: "100%",
    position: "absolute",
    bottom: verticalScale(45),
    paddingHorizontal: horizontalScale(24),
  },
  modalView: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(150),
  },
  invitationSendContent: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    borderRadius: radius.biggest,
    height: 400,
    alignItems: "center",
    paddingTop: verticalScale(36),
  },
  inviteCircleWrapper: {
    width: 100,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 5,
    borderColor: colors.purpleLinear,
    borderRadius: 50,
    backgroundColor: colors.white,
  },
  inviteCircleInner: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: colors.purpleLinear,
  },
  inviteSendButton: {
    position: "absolute",
    left: horizontalScale(24),
    right: horizontalScale(24),
    bottom: verticalScale(45),
  },
});
