import { horizontalScale, verticalScale } from "~/constants/metrics";
import { Platform, StyleSheet } from "react-native";
import {
  colors,
  getColorWithOpacity,
  radius,
} from "~/constants/designConstants";

const isIOS = Platform.OS === "ios";

export const styles = StyleSheet.create({
  containerWrapper: {
    width: "100%",
    paddingHorizontal: horizontalScale(24),
  },
  loaderContainer: {
    width: "100%",
    height: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  container: {
    position: "relative",
    width: "100%",
    flexDirection: isIOS ? "row" : "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.purpleLinear,
    borderRadius: radius.main,
    overflow: "hidden",
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(24),
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 5.62,
    elevation: 8,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    width: "100%",
  },
  backgroundCircles: {
    position: "absolute",
    right: -50,
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 7,
    borderColor: getColorWithOpacity(colors.white, 0.15),
    justifyContent: "center",
    alignItems: "center",
  },
  backgroundSecondCircle: {
    width: 114,
    height: 114,
    borderRadius: 58,
    backgroundColor: getColorWithOpacity(colors.white, 0.15),
  },
  image: {
    width: 68,
    height: 68,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 34,
    overflow: "hidden",
    backgroundColor: colors.lightBlue,
  },
  content: {
    alignItems: "flex-start",
    // marginLeft: horizontalScale(24),
  },
  title: {
    maxWidth: 240,
  },
  budgetInfoContainer: {
    maxWidth: 250,
    width: "100%",
    marginTop: verticalScale(8),
  },
  scaleContainer: {
    width: "100%",
    height: 6,
    borderRadius: 6,
    backgroundColor: getColorWithOpacity(colors.white, 0.4),
    alignItems: isIOS ? "flex-end" : "flex-start",
    overflow: "hidden",
  },
  scaleProgress: {
    width: 70,
    height: "100%",
    backgroundColor: colors.white,
    borderRadius: 6,
  },
  budgetInfo: {
    flexDirection: isIOS ? "row" : "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: verticalScale(6),
  },
  NISContainer: {
    flexDirection: isIOS ? "row" : "row-reverse",
    alignItems: "center",
  },
  NIS: {
    margin: horizontalScale(5),
    marginTop: verticalScale(-3),
  },
  emptyCard: {
    width: "100%",
    paddingVertical: verticalScale(20),
    paddingHorizontal: horizontalScale(8),
    paddingRight: isIOS ? 0 : horizontalScale(100),
    paddingLeft: isIOS ? horizontalScale(100) : 0,

    paddingBottom: verticalScale(85),
    backgroundColor: colors.secondaryRed,
    borderRadius: radius.biggest,
  },
  emptyCardRow: {
    width: "100%",
    flexDirection: isIOS ? "row-reverse" : "row",
    alignItems: "flex-start",
  },
  emptyCardText: {
    justifyContent: "flex-start",
  },
  emptyCardImage: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.grey,
    marginRight: isIOS ? horizontalScale(10) : horizontalScale(24),
    marginLeft: isIOS ? horizontalScale(15) : 0,

    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(10),
  },
  emptyCardButton: {
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: radius.main,
    backgroundColor: colors.white,
    position: "absolute",
    bottom: verticalScale(20),
    left: horizontalScale(24),
    right: horizontalScale(24),
  },
  emptyCardCircle: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 8,
    justifyContent: "center",
    alignItems: "center",
    borderColor: getColorWithOpacity(colors.white, 0.16),
    top: verticalScale(-15),
    left: horizontalScale(-30),
  },
  emptyCardCircleIOS: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 8,
    justifyContent: "center",
    alignItems: "center",
    borderColor: getColorWithOpacity(colors.white, 0.16),
    top: verticalScale(-15),
    right: horizontalScale(-40),
  },
  emptyCardCircleInner: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: getColorWithOpacity(colors.white, 0.16),
  },
});
