import {
  colors,
  getColorWithOpacity,
  radius,
} from "../../../../../../constants/designConstants";
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from "~/constants/metrics";
import { Platform, StyleSheet } from "react-native";

const isIOS = Platform.OS === "ios";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    backgroundColor: "#F2F2FA",
    position: "relative",
  },
  content: {
    marginTop: verticalScale(24),
    width: "100%",
    // height: "100%",
    backgroundColor: colors.white,
    borderRadius: radius.biggest,
    paddingVertical: verticalScale(25),
    paddingHorizontal: horizontalScale(24),
  },
  header: {
    flexDirection: isIOS ? "row-reverse" : "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  threeDotsButton: {
    width: 40,
    height: 40,
    borderRadius: radius.secondary,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.05,
    shadowRadius: 5.62,
    elevation: 81,
  },
  cardContainer: {
    width: "100%",
    height: 185,
    borderRadius: radius.main,
    marginTop: verticalScale(24),
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.05,
    shadowRadius: 5.62,
    elevation: 81,
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(24),
    position: "relative",
    justifyContent: "center",
  },
  cardCircle: {
    width: 200,
    height: 200,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 10,
    borderColor: getColorWithOpacity(colors.white, 0.08),
    position: "absolute",
    left: horizontalScale(-80),
    // right: isIOS ? horizontalScale(-80) : horizontalScale(0),
  },
  cardCircleIOS: {
    width: 200,
    height: 200,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 10,
    borderColor: getColorWithOpacity(colors.white, 0.08),
    position: "absolute",
    right: horizontalScale(-80),
  },
  cardCircleInner: {
    width: 166,
    height: 166,
    borderRadius: 83,
    backgroundColor: getColorWithOpacity(colors.white, 0.08),
  },
  cardNumber: {
    flexDirection: isIOS ? "row-reverse" : "row",
    alignItems: "center",
    marginTop: verticalScale(15),
    justifyContent: isIOS ? "flex-end" : "flex-start",
  },
  cardInfoContainer: {
    width: "100%",
    flexDirection: isIOS ? "row-reverse" : "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: verticalScale(25),
  },
  cardType: {
    position: "absolute",
    left: 0,
    bottom: verticalScale(0),
  },
  loaderContainer: {
    width: "100%",
    height: 200,
    justifyContent: "center",
    alignItems: "center",
  },
  button: {
    position: "absolute",
    bottom: verticalScale(205),
    right: horizontalScale(0),
    left: horizontalScale(0),
  },
  containerModal: {
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    height: "100%",
    paddingHorizontal: horizontalScale(24),
    paddingVertical: verticalScale(100),
    backgroundColor: colors.white,
  },
  menuModalContainer: {
    width: "100%",
    height: "100%",
    backgroundColor: getColorWithOpacity(colors.dark, 0.6),
    justifyContent: "flex-end",
  },
  menuModalContent: {
    width: "100%",
    height: 200,
    backgroundColor: colors.white,
    borderTopLeftRadius: radius.biggest,
    borderTopRightRadius: radius.biggest,
    paddingHorizontal: horizontalScale(24),
    paddingVertical: verticalScale(4),

  },
  modalRow: {
    width: "100%",
    flexDirection: isIOS ? "row-reverse" : "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginTop: verticalScale(24),
  },
  modalRowText: {
    marginLeft: isIOS ? horizontalScale(0) : horizontalScale(8),
    marginHorizontal: isIOS ? horizontalScale(8) : horizontalScale(0),
  },
  circleWrapper: {
    width: 84,
    height: 84,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: colors.purpleLinear,
    borderRadius: 50,
    backgroundColor: colors.white,
    marginTop: verticalScale(40),
  },
  circleInner: {
    width: 70,
    height: 70,
    borderRadius: 41,
    backgroundColor: colors.purpleLinear,
  },
  modalConfirm: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    position: "relative",
  },
  modalConfirmReturn: {
    position: "absolute",
    width: 40,
    height: 40,
    backgroundColor: colors.white,
    left: horizontalScale(4),
    top: verticalScale(24),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: radius.secondary,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.15,
    shadowRadius: 19.62,
    elevation: 81,
  },
  modalConfirmButtons: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: verticalScale(70),
  },
  modalConfirmDelete: {
    flex: 1,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: radius.main,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.09,
    shadowRadius: 14.62,
    elevation: 81,
    marginRight: horizontalScale(16),
  },
  modalConfirmRest: {
    flex: 1,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.purpleLinear,
    borderRadius: radius.main,
  },
  emptyContainer: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    paddingTop: verticalScale(65),
  },
});
