import {
  getColorWithOpacity,
  radius,
} from "./../../../../../../constants/designConstants";
import { horizontalScale, verticalScale } from "~/constants/metrics";
import { StyleSheet } from "react-native";
import { colors } from "~/constants/designConstants";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    paddingHorizontal: horizontalScale(24),
    marginTop: verticalScale(20),
  },
  emptyCardWrapper: {
    position: "relative",
    width: "100%",
    paddingHorizontal: horizontalScale(18),
    paddingVertical: verticalScale(16),
    borderRadius: radius.main,
    backgroundColor: colors.secondaryRed,
    overflow: "hidden",
    alignItems: "flex-start",
  },
  emptyCardBackgroundCircleWrapper: {
    position: "absolute",
    top: verticalScale(-60),
    // right: horizontalScale(-100),
    left: horizontalScale(-100),
    width: 280,
    height: 280,
    borderRadius: 140,
    borderWidth: 15,
    borderColor: getColorWithOpacity(colors.white, 0.09),
    justifyContent: "center",
    alignItems: "center",
  },
  emptyCardChildRow: {
    position: "relative",
    width: "100%",
    marginBottom: verticalScale(8),
    flexDirection: "row",
    alignItems: "center",
  },
  emptyCardChildIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.lightBlue,
    marginRight: horizontalScale(12),
  },
  emptyCardBackgroundCircle: {
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: getColorWithOpacity(colors.white, 0.09),
  },
  emptyCardText: {
    marginTop: verticalScale(8),
  },
  emptyCardButton: {
    width: "100%",
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: radius.main,
    marginTop: verticalScale(14),
  },
  emptyCardThreeDots: {
    position: "absolute",
    right: horizontalScale(0),
    top: verticalScale(0),
    width: 32,
    height: 32,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: getColorWithOpacity(colors.white, 0.28),
  },
  loadingContainer: {
    width: "100%",
    height: 152,
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(20),
  },
  myCardContainer: {
    width: "100%",
    // height: 152,
    backgroundColor: colors.purpleLinear,
    borderRadius: radius.main,
    position: "relative",
    justifyContent: "center",
    alignItems: "flex-start",
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(18),
  },
  myCardContainerIOS: {
    alignItems: "flex-end",
  },
  myCardBackgroundFirstCircle: {
    position: "absolute",
    left: horizontalScale(-80),
    width: 172,
    height: 172,
    borderRadius: 86,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 10,
    borderColor: getColorWithOpacity(colors.white, 0.08),
  },
  myCardBackgroundFirstCircleIOS: {
    position: "absolute",
    right: horizontalScale(-80),
    width: 172,
    height: 172,
    borderRadius: 86,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 10,
    borderColor: getColorWithOpacity(colors.white, 0.08),
  },
  myCardBackgroundFirstCircleInnner: {
    width: 138,
    height: 138,
    borderRadius: 69,
    backgroundColor: getColorWithOpacity(colors.white, 0.08),
  },
  myCardBackgroundSecondCircle: {
    position: "absolute",
    right: horizontalScale(-13),
    top: verticalScale(-35),
    width: 92,
    height: 92,
    borderRadius: 46,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 6,
    borderColor: getColorWithOpacity(colors.white, 0.08),
  },
  myCardBackgroundSecondCircleIOS: {
    position: "absolute",
    left: horizontalScale(-13),
    top: verticalScale(-35),
    width: 92,
    height: 92,
    borderRadius: 46,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 6,
    borderColor: getColorWithOpacity(colors.white, 0.08),
  },
  myCardBackgroundSecondCircleInnner: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: getColorWithOpacity(colors.white, 0.08),
  },
  myCardContent: {},
  meCardBudgetCount: {
    flexDirection: "row",
    alignItems: "flex-end",
  },
  myCardScaleContainer: {
    width: "100%",
    marginTop: verticalScale(12),
  },
  myCardScaleTopBar: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: verticalScale(8),
  },
  myCardScaleTopBarIOS: {
    flexDirection: "row-reverse",
  },
  myCardScale: {
    width: "100%",
    height: 6,
    borderRadius: 20,
    backgroundColor: getColorWithOpacity(colors.white, 0.5),
    justifyContent: "flex-start",
    flexDirection: "row",
  },
  myCardScaleIOS: {
    justifyContent: "flex-end",
  },
  myCardProgressBar: {
    height: "100%",
    borderRadius: 20,
    backgroundColor: colors.white,
  },
  myCardThreeDots: {
    position: "absolute",
    right: horizontalScale(16),
    top: verticalScale(16),
    width: 32,
    height: 32,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: getColorWithOpacity(colors.white, 0.28),
  },
  myCardThreeDotsIOS: {
    left: horizontalScale(16),
  },
  loaderContainer: {
    width: "100%",
    height: 152,
    alignItems: "center",
    justifyContent: "center",
  },
});
